# Basic
title: 何去丶何从
subtitle: 也许会点编程
description: 来与不来,我都在这里。
# 头像里面的标题
avatarTitle: makeclan
# 头像里面的描述
avatarDesc: 打码中...
url: "http://baixin.io"

# Comment
comment:
    disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 350687161 
    github: makeclan
    # twitter: 
    mail: makeclan@sina.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 72561c670680e7c46b206a0b14a45f93  

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3   
#     host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/makeclan/makeclan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


